make-mod-script: restore dependency on openssl-native
Commit 2e7ad537d2 ("make-mod-scripts: change how some kernel module tools
are built" removed the make-mod-scripts task, but also its depency on
openssl native. Add it back otherwise builds can fail with:

scripts/extract-cert.c:21:25: fatal error: openssl/bio.h: No such file or directory