mesa: Fix build on 32bit arches supporting 64bit time_t only
Fixes
../mesa-20.1.8/src/util/futex.h:47:19: error: use of undeclared identifier 'SYS_futex'; did you mean 'sys_futex'?
   return syscall(SYS_futex, addr1, op, val1, timeout, addr2, val3);
                  ^~~~~~~~~
                  sys_futex

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 21bdff510a7673ccf7f27f551b641a5ba84d656c)