python3: prefer valid dists when searching for entry points
When bitbake regenerates a sysroot due to upgrades it will remove any
previously installed files but keep the directories. This can result in
site-packages containing:

  setuptools/                  <-- the actual Python code
  setuptools-82.0.0.dist-info  <-- empty metadata directory
  setuptools-82.0.1.dist-info  <-- populated metadata directory

When importlib_metadata.entry_points() iterates the distributions it
will take the list of dists *in on-disk order* and then remove
duplicates. If the empty directory comes first in the unsorted directory
listing then that is the only one that is returned.

This eventually results in mysterious errors from setuptools:

  error: invalid command 'egg_info'

Solve this by sorting the distribution list so that valid dists are
first.

[ YOCTO #16235 ]

Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>